### ISSUE TITLE
Different pruning percentages for different layers

### ISSUE THREAD

**Issue by JeremyAlain** [jim-meyer/lottery_ticket_pruner#14]
Hi there, 
first of all thanks for the great repo. I was looking around for a long, long time and this seems to be the only tensorflow implementation of LTH in tensorflow 2.X. 

I wanted to ask you something. For my research I want to literally imitate the LTH paper. And they explain that for Fully connected layers, they use only half the pruning rate that they use in the other layers. Also for Convolutions, they use other pruning rates. 

Could you give me a hint, how and where in your implementation should I make changes to implement the above. 

Thanks so much 
cheers 
Jérémy

**Comment by jim-meyer** [comment]
It sounds to me like you would want to add a new pruning to the list of "local" (meaning per layer) pruning functions [here](https://github.com/jim-meyer/lottery_ticket_pruner/blob/master/lottery_ticket_pruner/lottery_ticket_pruner.py#L429).
You can use [one of the existing local pruning functions](https://github.com/jim-meyer/lottery_ticket_pruner/blob/master/lottery_ticket_pruner/lottery_ticket_pruner.py#L10-L37) as the basis for your new one.
But since the local pruning functions don't currently get passed any information about the layer they are pruning you would need to add something to the local pruning functions' argument list that you could use to determine what type of layer is being pruned. I *think* you could just add `layer` to the arguments passed [here](https://github.com/jim-meyer/lottery_ticket_pruner/blob/master/lottery_ticket_pruner/lottery_ticket_pruner.py#L436-L437), update the existing local pruning functions accordingly. Then your new local pruning function could look at this new `layer` argument to determine if it's a FC or conv layer.

**Comment by JeremyAlain** [comment]
Hi Jim; 
thanks so much for your answer. The first part was something I kind of figured out.  But as you say, I thought that currently there is no information about the layers passed to the pruning function. So thanks a lot for the tip on how to do that. It will speed up the whole process a lot thanks to your insight. 
I'll let you know if I can make it work. 

thanks so much

**Comment by JeremyAlain** [comment]
hey it worked out nicely. thanks for your help

**Comment by jim-meyer** [comment]
Glad it worked out. If you have a PR that you'd be willing to contribute
back to this repo for these changes that would be great.

jimm
